filter:
  excluded_paths:
    - 'tests/*'

checks:
  php:
    use_self_instead_of_fqcn: true
    return_doc_comments: true
    phpunit_assertions: true
    parameter_doc_comments: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: false
      order_alphabetically: false
    line_length:
      max_length: '120'
    no_goto: true
    fix_line_ending: true

coding_style:
  php:
    indentation:
      general:
        size: 1

build:
  tests:
    override:
      - vendor/bin/phpunit

  nodes:
    php81:
      environment:
        php: 8.1.13

    php82:
      environment:
        php: 8.2.24

    php83:
      environment:
        php: 8.3.12
