<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://new.webservice.namespace" targetNamespace="http://xml.amadeus.com" xmlns:pnr_reply_14_2="http://xml.amadeus.com/PNRACC_14_2_1A" xmlns:pnr_retrieve_14_2="http://xml.amadeus.com/PNRRET_14_2_1A">
	<wsdl:types>
		<xs:import schemaLocation="PNR_Reply_14_2_1A.xsd" namespace="http://xml.amadeus.com/PNRACC_14_2_1A"/>
        <xs:import schemaLocation="PNR_Retrieve_14_2_1A.xsd" namespace="http://xml.amadeus.com/PNRRET_14_2_1A"/>
	</wsdl:types>
	<wsdl:message name="PNR_Retrieve_14_2">
		<wsdl:part name="PNR_Retrieve_14_2" element="pnr_retrieve_14_2:PNR_Retrieve"/>
	</wsdl:message>
    <wsdl:message name="PNR_Reply_14_2">
        <wsdl:part name="PNR_Reply_14_2" element="pnr_reply_14_2:PNR_Reply"/>
    </wsdl:message>
	<wsdl:portType name="AmadeusWebServicesPT">
		<wsdl:operation name="PNR_Retrieve">
			<wsdl:input message="tns:PNR_Retrieve_14_2"/>
			<wsdl:output message="tns:PNR_Reply_14_2"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="AmadeusWebServicesBinding" type="tns:AmadeusWebServicesPT">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="PNR_Retrieve">
			<soap:operation soapAction="http://webservices.amadeus.com/PNRRET_14_2_1A"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="AmadeusWebServices">
		<wsdl:port name="AmadeusWebServicesPort" binding="tns:AmadeusWebServicesBinding">
			<soap:address location="https://dummy.webservices.amadeus.com/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>